location / {
    try_files $uri $uri/ @laravel;
}

location @laravel {
    rewrite ^ /index.php?$query_string last;
}

location ~ ^/index\.php(/|$) {
    try_files @heroku-fcgi @heroku-fcgi;
    internal;
}
