name: Sync to Google Drive

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: "1m0g_ireSV_8xDnlDXkarmPK9qSpjjyoz"
          filename: "./"
          mirrorDirectoryStructure: "true"
          overwrite: "true"

